# Generated by Django 3.1.7 on 2021-03-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='car_id',
            new_name='car',
        ),
    ]
